---
# file: roles/monit/tasks/tasks-Debian.yml

- name: Install monit packages
  apt: name={{ item }} state=installed update_cache=yes
  with_items: monit_packages
  tags: monit install

- name: Copy monit configuration
  template: src=debian.monitrc.j2 dest=/etc/monit/monitrc mode=600
  notify: restart monit
  tags: monit configure
